name: Publish
on:
  push:
    branches:
      - '*/main'
jobs:
  publish:
    name: Publish to Maven
    runs-on: ubuntu-20.04
    # Run only on main branch
    if: endsWith(github.ref, '/main')
    steps:
      - name: Shallow Clone (--recurse-submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Gradle & Caches
        uses: "./.github/actions/setup-gradle"

      - name: Publish with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_vs_maven_password: ${{ secrets.ORG_GRADLE_PROJECT_VS_MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_vs_maven_url: ${{ secrets.ORG_GRADLE_PROJECT_VS_MAVEN_URL }}
          ORG_GRADLE_PROJECT_vs_maven_username: ${{ secrets.ORG_GRADLE_PROJECT_VS_MAVEN_USERNAME }}
        run: |
          ./gradlew build publish --stacktrace --no-daemon
